### ISSUE TITLE
Does self hosted Ptorx require credits/contacting outside servers?

### ISSUE THREAD

**Issue by Bugsbane** [Xyfir/ptorx#16]
I'm interested in self hosting, and possibly later contributing to Ptorx.

I'm just wondering if this is a truly local, private install, or something that interfaces with your servers. 

1. Are credits still needed if self hosting?
2. Does Ptorx contact any domain other than the ones I'm setting it up on / the domains of my email aliases/addresses?
3. What local files does it need access to (/etc/hosts? dnsmasq config? sendmail?) Is it appropriate for shared hosting? (I have a local server and a shared hosting account)

Thanks!

**Comment by MrXyfir** [comment]
Hi @Bugsbane,

Everything is self hosted from top to bottom.

1. Credits are technically still used for simplicity in the code, however you'll be able to set your monthly credit limit to whatever number you like so that you don't run out.
2. It will be entirely isolated from ptorx.com and our servers.
3. You would need a server that you have root access to. Check the self hosting documentation for more info.

I'd love to see some contributions in the future! I actually no longer run Ptorx publicly (only a handful of users have access) so I'd like to see its code move strictly towards self-hosting.

Let me know if you have any questions!

**Comment by MrXyfir** [comment]
Closing because this isn't really an issue, but feel free to keep the discussion going 👍
