### ISSUE TITLE
Error: "Email is already in use"

### ISSUE THREAD

**Issue by Laiteux** [xyfir/ptorx#3]
Hello,

I recently added my domain to ptorx.com and was successfully able to use it.

I made the alias "contact@laiteux.dev" which I then decided to delete.

Now, when trying to create it again, I am getting this error: "Email is already in use"

I believe this is a problem on ptorx side, and would like you to check.

Regards,
Matt.

**Comment by MrXyfir** [comment]
Hi Matt,

Thanks for the report, but this is an intentional feature added to protect user privacy and security. Deleted aliases are kept in the database (only the address, without personal information) to prevent a different user from creating the same alias later and receiving the earlier user's messages!

You can delete the domain and add it to Ptorx again if you would like to clear out the deleted aliases and make them available again.
