### ISSUE TITLE
Enable account deletion button

### ISSUE THREAD

**Issue by MoralCode** [xyfir/ptorx#4]
I notice that in the [changelog](https://github.com/xyfir/ptorx/blob/c40d83d25671c2e7ff555f7547b777d0db68a5a5/CHANGELOG.md#L20) for version 6.8.0, you mentioned adding the ability for users to delete their accounts, but the "account" button seems to lead to a page that only allows the user to logout, reset a password, or change multifactor auth settings.

![Screenshot_20191213_163507](https://user-images.githubusercontent.com/17362949/70833802-a78d3200-1dc6-11ea-984e-9fb318eb2e22.png)

Based on the accownt repository screenshots, [it seems like the accownt page has an account deletion feature](https://camo.githubusercontent.com/436816a5dad8834f40fc83afe93be0514d6b9093/68747470733a2f2f692e696d6775722e636f6d2f753679415454662e706e67). Would it be possible to enable the "delete account" button on the accownt page for ptorx?

**Comment by MrXyfir** [comment]
Probably missed a config setting... Thanks for pointing this out. Will close once fixed.

**Comment by Laiteux** [comment]
? ^^

**Comment by MrXyfir** [comment]
I apologize for the delay here; I've been very busy with other projects. I've updated the config and it _should_ work but I haven't tested it. If it doesn't work, let me know.

**Comment by MoralCode** [comment]
i just tested it. and it works, but not in a particularly intuitive way:
from inspect element it looked like the app sent a `GET` request to `https://ptorx.com/api/users/delete?jwt=[a long string of characters that i assume are secret]` when clicking the delete button and the server responded with a `304 Not Modified`.

after supposedly deleting my account, i went to the ptorx homepage and was presented with a "go to app" button that returned me to my account that now should not exist. I presume it was a cached version because logging out and trying to log back in gave me `Error! User with email does not exist` as expected.

Also, does this deletion only delete the account-related records from the accownt portion of the app so that it no longer recognizes logins, or does it delete all information relating to that user (aliases, email addresses, email records etc.)

**Comment by MrXyfir** [comment]
It deletes the account and all linked objects

https://github.com/xyfir/ptorx/blob/23936ae54d361fad98f6ed051071867f07329088/server/lib/users/delete.ts#L5

The only distinction here is that aliases are simply 'marked' as deleted instead of actually removed from the database. It should be noted however that all personally-identifiable information is stripped from each alias when it is marked as deleted. The reason for this process is to prevent another user from claiming another user's previously-deleted alias and then having access to the previous user's address which would pose all sorts of privacy and security risks.
