### ISSUE TITLE
Not receiving emails anymore

### ISSUE THREAD

**Issue by Laiteux** [xyfir/ptorx#7]
It's been 18 days now, it simply won't work.

I tried sending myself emails and they're never arriving.

That's a big problem.

**Comment by MrXyfir** [comment]
My sincerest apologies for this. I'm guessing you ran out of credits? https://i.imgur.com/VkhVc65.png

I have been extremely busy lately and haven't had time to manage Ptorx and I don't foresee that changing in the near future. I didn't want to run a service that I couldn't properly maintain so I disabled the free credits and disabled purchasing new credits. This was probably a dumb and shortsighted move on my part but it was a quick fix to a personal problem. Not a good excuse, I know.

Given you've been so helpful, I'm giving you a free subscription, but I make no guarantees of service and I'd highly recommend looking for alternative solutions, even if it's just self-hosting Ptorx with your own domains.

And just to be clear, I have no plans of taking Ptorx offline, especially since I have hundreds of my own emails and accounts linked up to it, but I just want to minimize the risk for other people since no updates are currently planned.

Let me know if there's anything else I can do for you.

**Comment by Laiteux** [comment]
Hello,

First of all: Thanks a lot for the plan, I truly appreciate you gave me it for free even tho I could have paid.

I really love Ptorx so even without any guarantee I'll most likely keep using it, simply because it's exactly what I need and in my opinion is way better than other similar services.

If it ever becomes disfunctional for some reason, I'll self-host it but for now I feel confident using the official website.

Thanks again for the plan.

Much love.
